### ISSUE TITLE
Remove IP restrictions

### ISSUE THREAD

**Issue by PaulDuvall** [stelligent/nando_automation_demo#11]
Currently there are CIDR block restrictions on accessing environments. This makes is very difficult to run a demo.
Priority: High

**Comment by nand0p** [comment]
need to ensure jenkins security is working, as otherwise, anyone could make/modify a job so as to launch hundreds of expensive instances, or delete all of s3 buckets

**Comment by PaulDuvall** [comment]
Delete _all_ of the S3 buckets? Is there a way we can use a more restrictive IAM account that doesn't delete all buckets?

**Comment by nand0p** [comment]
we could update the jenkins S3 policy to not allow deletion. currently it does allow s3:*.  so we could lock down to only a single bucket (the one created elsewhere in template)

```
    "NandoDemoJenkinsIAMPolicy": {
            "Action": [
              "autoscaling:Describe*",
              "cloudformation:DescribeStacks",
              "ec2:Describe*",
              "s3:*",
              "codedeploy:*",
              "elasticbeanstalk:*"
            ],
```

launching ec2 instances is not currently allowed by Jenkins, so disregard earlier statement about launching instances. codedeploy and elasticbeanstalk permissions should be locked down further however, instead of being wildcards

**Comment by trikosuave** [comment]
should be good.

**Comment by nand0p** [comment]
Patrick, can we further lock down the codedeploy:\* and elastickbeanstalk:\* ?

also maybe the S3 section should only allow access to nando-automation-demo\* ?

```
            "Action": [
              "autoscaling:Describe*",
              "cloudformation:DescribeStacks",
              "ec2:Describe*",
              "s3:Get*",
              "s3:List*",
              "elasticbeanstalk:*",
              "codedeploy:*"
            ],
```

**Comment by NickDeClario** [comment]
After looking through everything and discussing with Nando, elasticbeanstalk privileges have been fully removed from the policy.  The elasticbeanstalk application container is created during deployment, the Jenkins jobs simply push nando_demo.zip to S3.

I ran through a successful deploy with the following Jenkins policy change:

```
        "Action": [                                                         
          "autoscaling:Describe*",                                          
          "cloudformation:DescribeStacks",                                  
          "ec2:Describe*",                                                  
          "codedeploy:Get*",                                                
          "codedeploy:List*",                                               
          "codedeploy:CreateDeployment",                                    
          "codedeploy:RegisterApplicationRevision"                          
        ],
```

I believe this is the last requirement to resolve this issue.

**Comment by NickDeClario** [comment]
Nando brought this to my attention.  The minimum codedeploy policy that was added allows the possibility of malicious code to be pushed out from the jenkins server.  This requires the jenkins server to be compromised and likely wouldn't be an issue in an actual, production environment where Jenkins wouldn't be public facing.  

One idea we came up with is to create a cloudwatch script that can monitor the process and the script itself.  Since the security groups limit access to only port 80, we can write a script that will assure that the python flask process is connected to port 80 and confirm the Python code itself matches an md5sum generated at deployment time.  Of course, if these conditions are not met, we are notified via cloudwatch.

A new ticket will be created for this.
