### ISSUE TITLE
Non Private AMIs

### ISSUE THREAD

**Issue by PaulDuvall** [stelligent/nando_automation_demo#26]
Last I heard, we were using a private AMI for the demo instances. Will need to make this public so that open source version continues to run

**Comment by trikosuave** [comment]
This is actually fixed in a different manner. The python script has a dictionary that one can point to their own AMIs. If that dictionary doesn't have the region specified or the AMI it points to can't be found (if someone outside of Stelligent runs with our AMI ids in there) it will build using the default public AMI and still work perfectly. Providing an AMI with Python/Puppet/Jenkins installed will cut down build time by a couple of minutes.
